// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teamup.Data;

#nullable disable

namespace Teamup.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260420183412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Teamup.Data.Game", b =>
                {
                    b.Property<int>("Game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Game_id");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Teamup.Data.Request", b =>
                {
                    b.Property<int>("Request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Game_id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Request_id");

                    b.HasIndex("Game_id");

                    b.HasIndex("User_id");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("Teamup.Data.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Sub")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("User_id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Teamup.Data.Request", b =>
                {
                    b.HasOne("Teamup.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("Game_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Teamup.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
